### ISSUE TITLE
left CharacterHand should be in character-head and not in coat-1 files

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Insurgent-of-Myjava#74]
currently these files contain a light hand:
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/ch-0-coat-1-blue.svg
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/ch-0-coat-1-green.svg
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/ch-0-coat-1-red.svg

causing the wrong hand for some characters:
![Screenshot 2019-03-20 at 16 20 34](https://user-images.githubusercontent.com/902958/54696966-1043c880-4b2d-11e9-8f3e-4500e403ce4f.png)

Not having the left hands in the 'CharacterHead' files, causes some coats without hands:
![Screenshot 2019-03-20 at 16 24 16](https://user-images.githubusercontent.com/902958/54697186-6d3f7e80-4b2d-11e9-8176-1fcdf1e0df96.png)

So: Left hands should be included in the 'CharacterHead' files (just like the right hands are):
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/character-0-head.svg
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/character-1-head.svg
- https://github.com/unfoldcollective/Insurgent-of-Myjava/blob/master/app/static/character-2-head.svg

**Comment by matopysny** [comment]
The problem is more complex. All legwear items include left hand and 1 shape of torso wear. A heavy coat is handless because it was meant like: the character has his/her hand in the pocket of his/her heavy coat.
To fix this problem I need to do:
A:
1-export all legwear items without the left hand (9 pieces)
2-redraw slave of the heavy coat for every color
3-export 2 shapes of torso wear items (6 pieces)
4-redraw hand and add it to the "head" layer for every character (3 pieces)

If it works pixel perfect I will need to:
B:
1-redraw slave of the heavy coat for every color
2-redraw hand and add it to the "head" layer for every character. So this top layer will cover white left hand (3 pieces)

I'm going to do scenario B for now. If it will not be enough I will do 2 more steps from A scenario afterwards

**Comment by phivk** [comment]
I didn't know the hand was covered by the pocket of the heavy coat. If that
is the case this doesn't have to be changed.

The issue of the white had stuck to a non white character will still need
to be fixed of course.

**Comment by matopysny** [comment]
To solve this problem properly as (I suggested before) will take me almost a day work. I tried a shortcut solution for now (might be satisfactory). Only Roma-gipsy character has added left hand in the "ch-3-head.svg" file. This hand is slightly bigger than the white one. The brown hand should cover the white one. There is only one not looking perfect scenario:

<img width="449" alt="Screenshot 2019-03-22 at 00 22 35" src="https://user-images.githubusercontent.com/31274508/54791360-d44a5980-4c39-11e9-8e2b-d2bdb75afac8.png">

with other clothing items, it should work smoothly. Please let me know if you @phivk would like to go with the proper solution (redrawing 6 pieces and re-exporting 18). Unfortunately I will have the capacity to prepare it during next week.

**Comment by phivk** [comment]
thanks @matopysny. unfortunately we can't afford to spend another day next week. I'll integrate your shortcut solution now.
